### ISSUE TITLE
 Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by Ibom99** [BolajiAyodeji/image-search-app#24]
I tried to analyze your website using Lighthouse and realized that your logo image does not have an `alt` text. I'd like to fix this.

![Screenshot (138)](https://user-images.githubusercontent.com/104465078/183846510-07d9bbc9-c237-4cba-96ac-b0f4a97bd1d1.png)

**Comment by BolajiAyodeji** [comment]
Hi @Ibom99, thanks for submitting this issue!

Issue #21 already fixes this; hence I'll be closing this issue. Please feel free to pick up something else; thank you.
