### ISSUE TITLE
Image elements do not have [alt] attributes.

### ISSUE THREAD

**Issue by judeokeleke** [BolajiAyodeji/image-search-app#25]
After analyzing your website using lighthouse, i realized your logo image dosen't have an ' alt ' text, i would like to fix this.
![image](https://user-images.githubusercontent.com/106659305/183868886-1769099a-b890-41f6-ac92-bd039ed3e570.png)

**Comment by BolajiAyodeji** [comment]
Hi @judeokeleke, thanks for submitting this issue!

Issue #21 already fixes this; hence I'll be closing this issue. Please feel free to pick up something else; thank you.
