### ISSUE TITLE
image elements do not have explicit width and height

### ISSUE THREAD

**Issue by Misturaht** [BolajiAyodeji/image-search-app#30]
I have gone through and analyzed your website using lighthouse and I realised that your image elements do not have width and height attributes. I would love to help you with that
![issue](https://user-images.githubusercontent.com/46754000/184104727-d95a6590-7166-4b78-a55e-11579119df40.JPG)

**Comment by BolajiAyodeji** [comment]
Hi @Misturaht, thanks for submitting this issue!

Issue #27 already proposed this; hence I'll be closing this issue. Please feel free to pick up something else; thank you.
