### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by Code-Trillz** [BolajiAyodeji/image-search-app#32]
I tried to analyze your website and realized that the logo image does not have an `alt` text. I would like to fix it.

![image](https://user-images.githubusercontent.com/73820604/184119819-d0169371-e2d1-423a-80ce-65f087925ad9.png)

**Comment by BolajiAyodeji** [comment]
Hi @Code-Trillz, thanks for submitting this issue!

PR #21 already fixes this; hence I'll be closing this issue. Please feel free to pick up something else; thank you.
