### ISSUE TITLE
Manifest doesn't have a maskable icon

### ISSUE THREAD

**Issue by Abdul-k1** [BolajiAyodeji/image-search-app#43]
Hello Bolaji,

I analysed your website using Lighthouse and i discovered that the Manifest doesn't have a maskable icon.

<img width="594" alt="Screenshot 2022-08-16 at 14 51 44" src="https://user-images.githubusercontent.com/14153036/184898515-d98362fe-4864-4b0b-9bc0-3e2091c865f5.png">

should i go ahead and fix this?

**Comment by BolajiAyodeji** [comment]
Sure, please go ahead!

**Comment by BolajiAyodeji** [comment]
Fixed in #44.
