### ISSUE TITLE
Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by thebenjaminibe** [BolajiAyodeji/image-search-app#45]
I tried to analyze your website using Lighthouse and realized that the logo image does not have an 'alt' text. I'd like to fix this.

![img](https://user-images.githubusercontent.com/97017874/185047658-80edbd03-37d7-4e4c-ab03-a7edee7e5d32.png)

**Comment by BolajiAyodeji** [comment]
Thanks for raising this issue! The issue is already fixed in #21. I'd be closing this now; thank you.
