### ISSUE TITLE
Does not provide a valid apple-touch-icon

### ISSUE THREAD

**Issue by Sunnybrown** [BolajiAyodeji/image-search-app#48]
I attempted analyzing your website and discovered that there is no valid apple touch icon. I would be more tan glad to fix this.
![Capture 2](https://user-images.githubusercontent.com/90167802/186173194-986de133-041a-4198-bacf-c6bf3d943edf.PNG)

**Comment by BolajiAyodeji** [comment]
Sure, please go ahead @Sunnybrown.

**Comment by BolajiAyodeji** [comment]
Hi @Sunnybrown; thank you for raising this. Someone has already picked this up in #39.
